---
name: 'DCS Lua Composer'
description: 'Combines all Lua source files for a project into one sanitized, mission-ready script for DCS World for easier development.'
author: 'YoloWingPixie'

branding:
  icon: 'layers'
  color: 'purple'

inputs:
  source_directory:
    description: 'Source directory containing all Lua and text files. Relative to the repository root.'
    required: true
    default: 'src'
  output_file:
    description: 'Path for the final combined Lua file. Relative to the repository root.'
    required: true
    default: 'dist/mission_script.lua'
  header_file:
    description: 'Optional: Relative path *from source_directory* to the header file. Included verbatim at the top.'
    required: false
    default: ''
  namespace_file:
    description: 'Required: Relative path *from source_directory* to the namespace definition file. Sanitized.'
    required: true
  entrypoint_file:
    description: 'Required: Relative path *from source_directory* to the main entry point file. Loaded after core modules. Sanitized.'
    required: true
  footer_file:
    description: 'Optional: Relative path *from source_directory* to the footer file. Included verbatim at the bottom.'
    required: false
    default: ''
  dcs_strict_sanitize:
    description: >-
      If true (default), fails build on os, io, lfs usage.
      `loadlib` is always removed with a warning.
      Print/log are always transformed.
    required: false
    default: 'true'

outputs:
  built_file_path:
    description: 'The path to the generated Lua file.'
    value: ${{ inputs.output_file }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        uv --version

    - name: Sync environment for composer script
      shell: bash
      run: |
        # cd to the action path because pyproject.toml and uv.lock are there
        cd "${{ github.action_path }}"
        uv sync --all-extras

    - name: Run DCS Lua Compose Script
      shell: bash
      env:
        PYTHONWARNINGS: 'ignore:.*invalid escape sequence.*:SyntaxWarning:luaparser\.printers'
      run: |
        # cd to the action path to ensure uv run finds the synced environment
        cd "${{ github.action_path }}"
        uv run python composer.py \
          "${{ github.workspace }}/${{ inputs.source_directory }}" \
          "${{ github.workspace }}/${{ inputs.output_file }}" \
          --namespace "${{ inputs.namespace_file }}" \
          --entrypoint "${{ inputs.entrypoint_file }}" \
          ${{ inputs.header_file != '' && format('--header "{0}"', inputs.header_file) || '' }} \
          ${{ inputs.footer_file != '' && format('--footer "{0}"', inputs.footer_file) || '' }} \
          --dcs-strict-sanitize "${{ inputs.dcs_strict_sanitize }}"
