---
name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'action.yml'
      - 'composer.py'
      - 'pyproject.toml'
      - 'uv.lock'
      - 'tests/test_composer.py'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'action.yml'
      - 'composer.py'
      - 'pyproject.toml'
      - 'uv.lock'
      - 'tests/test_composer.py'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

jobs:
  test-and-lint:
    name: Test, Lint & Format Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate VERSION file (no trailing whitespace)
        shell: bash
        run: |
          VERSION_CONTENT=$(cat VERSION)
          if [[ "$VERSION_CONTENT" != "$(echo -n "$VERSION_CONTENT" | sed 's/[[:space:]]*$//')" ]]; then
            echo "::error::VERSION file has trailing whitespace. Please remove it."
            exit 1
          fi
          echo "VERSION file whitespace check passed."

      - name: Check VERSION file updated on PR
        if: github.event_name == 'pull_request'
        run: |
          echo "Base ref: ${{ github.base_ref }}"
          git fetch origin ${{ github.base_ref }}

          BASE_VERSION=$(cat VERSION) # Read current branch version first
          # Temporarily checkout base ref to read its VERSION file
          git checkout origin/${{ github.base_ref }} -- VERSION
          PR_BASE_VERSION=$(cat VERSION)
          # Checkout back to PR commit's VERSION file state
          git checkout HEAD -- VERSION

          echo "Base (origin/${{ github.base_ref }}) VERSION: $PR_BASE_VERSION"
          echo "Current PR branch VERSION: $BASE_VERSION"

          if [[ "$BASE_VERSION" == "$PR_BASE_VERSION" ]]; then
            echo "::error::VERSION file has not been updated in this PR compared to branch '${{ github.base_ref }}'."
            echo "::error::Please increment the version."
            exit 1
          else
            echo "VERSION file has been updated. Proceeding..."
          fi
        shell: bash

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        shell: bash
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          uv --version

      - name: Sync environment with uv
        shell: bash
        run: |
          uv sync --all-extras # Installs from uv.lock (main and dev dependencies)
          echo "Python from venv: $(uv run python --version)"
          echo "Verifying pytest installation..."
          uv run pytest --version
          echo "Verifying ruff installation..."
          uv run ruff --version
          echo "Verifying yamllint installation..."
          uv run yamllint --version

      - name: Run Pytest
        shell: bash
        run: |
          uv run pytest tests/test_composer.py

      - name: Run Ruff Linter
        shell: bash
        run: |
          uv run ruff check .

      - name: Run Ruff Formatter Check
        shell: bash
        run: |
          uv run ruff format --check .

      - name: Run Pre-Commit Checks
        shell: bash
        run: |
          uv run pre-commit run --all-files

      - name: Run YAML Lint
        shell: bash
        run: |
          uv run yamllint .
